# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-13 19:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0010_auto_20200210_0101'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(default='', max_length=100, verbose_name='Ad\u0131n\u0131z/Name')),
                ('lastName', models.CharField(default='', max_length=100, verbose_name='Soyad\u0131n\u0131z/Lastname')),
                ('phone', models.CharField(default=0, max_length=11, verbose_name='Telefon Numarasi/Phone Number')),
                ('address', models.TextField(default='', help_text='Adres')),
                ('profileImage', models.ImageField(blank=True, null=True, upload_to='profileimg', verbose_name='Resim Ekle/Add Picture')),
                ('completedOrders', models.ManyToManyField(blank=True, related_name='_userprofile_completedOrders_+', to='order.Order')),
                ('currentOrders', models.ManyToManyField(blank=True, related_name='_userprofile_currentOrders_+', to='order.Order')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
