# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-03 11:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='username2',
            field=models.CharField(default=django.utils.timezone.now, max_length=30, verbose_name=b'Username'),
            preserve_default=False,
        ),
    ]
