# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-03 14:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_username2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='username2',
        ),
    ]
