# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-09 06:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20200209_0903'),
        ('users', '0002_auto_20200209_0922'),
    ]

    operations = [
       
    ]
