# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-08 22:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
        ('users', '0003_remove_userprofile_username2'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='completedOrders',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Tamamlanan Siparisler/Completed Orders+', to='product.Product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='currentOrders',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Simdiki Siparisler/Current Orders+', to='product.Product'),
            preserve_default=False,
        ),
    ]
