# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-09 06:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_order_product'),
        ('users', '0003_auto_20200209_0922'),
    ]

    operations = [
        
    ]
