# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-08 23:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200209_0141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='completedOrders',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Tamamlanan Siparisler/Completed Orders+', to='product.Product'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='currentOrders',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Simdiki Siparisler/Current Orders+', to='product.Product'),
        ),
    ]
