# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-08 23:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20200209_0203'),
        ('users', '0005_auto_20200209_0211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='completedOrders',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='completedOrders',
            field=models.ManyToManyField(blank=True, null=True, related_name='_userprofile_completedOrders_+', to='product.Product'),
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='currentOrders',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='currentOrders',
            field=models.ManyToManyField(blank=True, null=True, related_name='_userprofile_currentOrders_+', to='product.Product'),
        ),
    ]
