# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-09 20:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_auto_20200209_2342'),
        ('users', '0005_auto_20200209_1028'),
    ]

    operations = [
        
    ]
