# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-08 23:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200209_0214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='completedOrders',
            field=models.ManyToManyField(blank=True, related_name='_userprofile_completedOrders_+', to='product.Product'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='currentOrders',
            field=models.ManyToManyField(blank=True, related_name='_userprofile_currentOrders_+', to='product.Product'),
        ),
    ]
