# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-09 21:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_order_guestprofile'),
        ('users', '0007_auto_20200210_0041'),
    ]

    operations = [
        
    ]
