# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-09 00:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200209_0226'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='fullName',
            field=models.CharField(default='', max_length=100, verbose_name='Ad\u0131n\u0131z/Name'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone',
            field=models.IntegerField(default=0, verbose_name='Telefon Numarasi/Phone Number'),
        ),
    ]
