# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-09 22:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_auto_20200210_0101'),
        ('users', '0008_auto_20200210_0049'),
    ]

    operations = [
        
    ]
