# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-09 01:00
from __future__ import unicode_literals

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20200209_0348'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='address',
            field=models.TextField(blank=True, help_text='Telefon Numaras\u0131'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Telefon Numarasi/Phone Number'),
        ),
    ]
