# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-09 01:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20200209_0412'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='fullName',
            new_name='firstName',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='lastName',
            field=models.CharField(default='', max_length=100, verbose_name='Ad\u0131n\u0131z/Name'),
        ),
    ]
