# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-09 01:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20200209_0425'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='urunMiktari',
            field=models.IntegerField(default=1, verbose_name='\xdcr\xfcn Miktar\u0131/Product Amount'),
        ),
    ]
