# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-09 02:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_userprofile_urunmiktari'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='urunMiktari',
            new_name='productAmount',
        ),
    ]
