# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-09 02:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20200209_0519'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='productAmount',
        ),
    ]
