# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-08 20:29
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, verbose_name=b'Title')),
                ('content', ckeditor.fields.RichTextField()),
                ('createdDate', models.DateTimeField(auto_now_add=True, verbose_name=b'Created Date')),
                ('isPrivate', models.BooleanField(default=False, verbose_name='Gizli/Private')),
                ('productImage', models.ImageField(blank=True, null=True, upload_to=b'', verbose_name='Resim Ekle/Add Picture')),
                ('productPrice', models.IntegerField(verbose_name='Fiyat/Price')),
            ],
            options={
                'ordering': ['-createdDate'],
            },
        ),
    ]
