# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-09 06:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productPrice',
            field=models.FloatField(verbose_name='Fiyat/Price'),
        ),
    ]
