# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-08 23:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='orderedDate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name=b'Ordered Date'),
            preserve_default=False,
        ),
    ]
