# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-09 20:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredient', '0001_initial'),
        ('product', '0002_auto_20200209_0919'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ingredients',
            field=models.ManyToManyField(blank=True, related_name='_product_ingredients_+', to='ingredient.Ingredient'),
        ),
        migrations.AlterField(
            model_name='product',
            name='createdDate',
            field=models.DateTimeField(auto_now_add=True, verbose_name=b'Yaz\xc4\xb1lma Tarihi'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=100, verbose_name=b'Ba\xc5\x9fl\xc4\xb1k'),
        ),
    ]
