# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-13 19:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20200209_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sold',
            field=models.IntegerField(default=0, verbose_name='Times Sold'),
        ),
    ]
