# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-09 02:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_product_orderstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='productAmount',
            field=models.IntegerField(default=1, verbose_name='\xdcr\xfcn Miktar\u0131/Product Amount'),
        ),
    ]
