# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-09 03:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_product_productamount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='orderStatus',
        ),
        migrations.RemoveField(
            model_name='product',
            name='orderedDate',
        ),
        migrations.RemoveField(
            model_name='product',
            name='productAmount',
        ),
    ]
