# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-30 02:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20200130_0338'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='iscompleted',
            field=models.BooleanField(default=False, verbose_name='Is Completed'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='content',
            field=models.TextField(verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='date',
            field=models.DateTimeField(default='', verbose_name='Time'),
        ),
    ]
