# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-30 05:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20200130_0633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Baslik'),
        ),
    ]
