# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-01 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_auto_20200201_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='isPrivate',
            field=models.BooleanField(default=False, verbose_name='Gizli/Private'),
        ),
    ]
