# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-01 20:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_article_isprivate'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='articleImage',
            field=models.FileField(blank=True, null=True, upload_to=b'', verbose_name='Resim Ekle/Add Picture'),
        ),
    ]
