# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-01 21:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_article_articleimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-createdDate']},
        ),
    ]
