# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-01 21:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0008_auto_20200202_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='articleImage',
            field=models.ImageField(blank=True, null=True, upload_to=b'', verbose_name='Resim Ekle/Add Picture'),
        ),
    ]
