# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-09 20:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='\u0130sim/Name')),
                ('ingredientImage', models.ImageField(blank=True, null=True, upload_to=b'', verbose_name='Resim Ekle/Add Picture')),
            ],
        ),
    ]
