# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-09 21:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GuestProfile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(default='', max_length=100, verbose_name='Ad\u0131n\u0131z/Name')),
                ('lastName', models.CharField(default='', max_length=100, verbose_name='Soyad\u0131n\u0131z/Lastname')),
                ('phone', models.CharField(default=0, max_length=11, verbose_name='Telefon Numarasi/Phone Number')),
                ('address', models.TextField(default='', help_text='Adres')),
            ],
        ),
    ]
