# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-08 22:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField(max_length=4000, verbose_name='Yorum Ekle')),
                ('createdDate', models.DateTimeField(auto_now_add=True, verbose_name='Olu\u015fturulma Tarihi')),
                ('userImage', models.ImageField(blank=True, null=True, upload_to=b'', verbose_name='Resim Ekle/Add Picture')),
                ('comments2', models.TextField(blank=True, max_length=4000, null=True, verbose_name='Yorum Ekle')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Yazar')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product')),
            ],
        ),
    ]
