# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-09 03:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, verbose_name=b'Title')),
                ('productImage', models.ImageField(blank=True, null=True, upload_to=b'', verbose_name='Resim Ekle/Add Picture')),
                ('productAmount', models.IntegerField(default=1, verbose_name='\xdcr\xfcn Miktar\u0131/Product Amount')),
                ('totalPrice', models.FloatField(verbose_name='Fiyat/Price')),
                ('orderedDate', models.DateTimeField(default='', verbose_name=b'Ordered Date')),
                ('orderStatus', models.CharField(default='Sipari\u015f Al\u0131nd\u0131.', max_length=100, verbose_name=b'Order Status')),
            ],
        ),
    ]
