# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-09 03:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='isGuest',
            field=models.BooleanField(default=False, verbose_name='Misafir/Guest'),
        ),
    ]
