# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-09 06:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20200209_0919'),
        ('order', '0004_auto_20200209_0903'),
    ]

    operations = [
       
    ]
