# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-09 06:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20200209_0919'),
        ('order', '0005_order_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='product.Product', verbose_name='\xdcr\xfcn/Product'),
            preserve_default=False,
        ),
    ]
