# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-09 20:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_order_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='orderStatus',
            field=models.CharField(default='Sipari\u015f Al\u0131nd\u0131.', max_length=100, verbose_name=b'Sipari\xc5\x9f Durumu'),
        ),
        migrations.AlterField(
            model_name='order',
            name='orderedDate',
            field=models.DateTimeField(default='', verbose_name=b'Sipari\xc5\x9f Zaman\xc4\xb1'),
        ),
        migrations.AlterField(
            model_name='order',
            name='title',
            field=models.CharField(max_length=100, verbose_name=b'Ba\xc5\x9fl\xc4\xb1k'),
        ),
    ]
