# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-09 21:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0001_initial'),
        ('order', '0008_auto_20200209_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='guestProfile',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='guests.GuestProfile', verbose_name='Misafir Profil/Guest Profile'),
            preserve_default=False,
        ),
    ]
