# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-09 22:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_order_guestprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='guestProfile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='guests.GuestProfile', verbose_name='Misafir Profil/Guest Profile'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, default=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullan\u0131c\u0131/User'),
        ),
    ]
